apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multicluster-deployer
  namespace: assessment
rules:
  - apiGroups:
      - networking.gke.io
    resources:
      - frontendconfigs
      - multiclusteringresses
      - multiclusterservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloud.google.com
    resources:
      - backendconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
