apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: app-a
    app.kubernetes.io/part-of: schwab-assessment
  name: app-a
  namespace: assessment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-a
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/name: app-a
        app.kubernetes.io/part-of: schwab-assessment
    spec:
      containers:
        - args:
            - |
              envsubst '$ASSESSMENT_REGION' < /etc/nginx/templates/nginx.conf.template > /tmp/nginx.conf
              exec nginx -c /tmp/nginx.conf -g 'daemon off;'
          command:
            - /bin/sh
            - -ceu
          env:
            - name: ASSESSMENT_REGION
              value: ""
          image: docker.io/nginxinc/nginx-unprivileged@sha256:45ce1e2e699234253d1def7baa96218a5d00b498d1ba0cbb1a17b6bdf73d1351
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
          name: app-a
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 2
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: nginx-template
              readOnly: true
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/secrets/assessment
              name: app-a-secrets
              readOnly: true
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: app-a
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: app-a
          maxSkew: 1
          nodeTaintsPolicy: Honor
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: app-a
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - configMap:
            items:
              - key: nginx.conf.template
                path: nginx.conf.template
            name: app-a-nginx
          name: nginx-template
        - emptyDir: {}
          name: tmp
        - csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: app-a-secrets
          name: app-a-secrets
